### ISSUE TITLE
pydocmd fails with error when building documentation

### ISSUE THREAD

**Issue by pmolfese** [BEL-Public/mffpy#111]
Attempting to build documentation for mffpy, receive error in pydocmd command:

```
$> pydocmd build
/Users/molfesepj/opt/miniconda3/envs/mffpy/bin/pydocmd:28: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/Users/molfesepj/opt/miniconda3/envs/mffpy/bin/pydocmd", line 228, in <module>
    file_i = insp_file(in_f)
  File "/Users/molfesepj/opt/miniconda3/envs/mffpy/bin/pydocmd", line 54, in insp_file
    mod_inst = imp.load_source('', file_name)
  File "/Users/molfesepj/opt/miniconda3/envs/mffpy/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "/Users/molfesepj/opt/miniconda3/envs/mffpy/lib/python3.9/imp.py", line 157, in get_data
    return super().get_data(path)
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
IsADirectoryError: [Errno 21] Is a directory: 'build'
```

cc: @jbteves

**Comment by ephathaway** [comment]
Can you post the contents of your `pydocmd` file? It looks like it's trying to treat the `build` directory like a python file.

**Comment by pmolfese** [comment]
Some weird conflicting packages in my homebrew install. Fixed that and now it builds.
