### ISSUE TITLE
Error in `get_physical_samples_from_epoch` when time range is small

### ISSUE THREAD

**Issue by ianbrown9475** [BEL-Public/mffpy#79]
Another application using mffpy encountered this error when I tested with a segmented MFF with a start time of 0 and an end time <= 500.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mffpy/reader.py", line 311, in get_physical_samples_from_epoch
    t0, dt, channels, block_slice=epoch.block_slice)
  File "/usr/local/lib/python3.6/site-packages/mffpy/reader.py", line 256, in get_physical_samples
    for typ, blob in self._blobs.items()
  File "/usr/local/lib/python3.6/site-packages/mffpy/reader.py", line 257, in <dictcomp>
    if typ in channels
  File "/usr/local/lib/python3.6/site-packages/mffpy/bin_files.py", line 91, in get_physical_samples
    t0, dt, block_slice=block_slice)
  File "/usr/local/lib/python3.6/site-packages/mffpy/raw_bin_files.py", line 92, in read_raw_samples
    block_data = self._read_blocks(A, B)
  File "/usr/local/lib/python3.6/site-packages/mffpy/raw_bin_files.py", line 169, in _read_blocks
    return np.concatenate(data, axis=1)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
```

Tagging @jusjusjus

**Comment by jusjusjus** [comment]
Addressed here: https://github.com/BEL-Public/mffpy/pull/78

**Comment by ianbrown9475** [comment]
Yep, now we just need to create a new signal-service release and update FLOW to use that new release
